[workspace]
members = ["backend", "frontend", "frontend-server"]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["Alessandro Lavelli"]
description = "Example of a web application totally written in Rust"
edition = "2024"
license = "Apache 2.0"

[workspace.dependencies]
